# Project 2 (14 th May 22)
Author : Anuradha Ghotekar

Goal is to predict "Item_Outlet_Sales"

The Problem Description
The data scientists at BigMart have collected 2013 sales data for 1559 products across 10 stores in different cities. Also, certain attributes of each product and store have been defined. The aim is to build a predictive model and find out the sales of each product at a particular store(Item_Outlet_Sales[Ycol]).

Using this model, BigMart will try to understand the properties of products and stores which play a key role in increasing sales.

# Read and preview data

In [1]:
import pandas as pd
A= pd.read_csv("D:/My work/Data science course/Datasets/Train.csv")
from warnings import filterwarnings
filterwarnings("ignore")

In [2]:
A.head(15)

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales
0,FDA15,9.300,Low Fat,0.016047,Dairy,249.8092,OUT049,1999,Medium,Tier 1,Supermarket Type1,3735.1380
1,DRC01,5.920,Regular,0.019278,Soft Drinks,48.2692,OUT018,2009,Medium,Tier 3,Supermarket Type2,443.4228
2,FDN15,17.500,Low Fat,0.016760,Meat,141.6180,OUT049,1999,Medium,Tier 1,Supermarket Type1,2097.2700
3,FDX07,19.200,Regular,0.000000,Fruits and Vegetables,182.0950,OUT010,1998,NaN,Tier 3,Grocery Store,732.3800
4,NCD19,8.930,Low Fat,0.000000,Household,53.8614,OUT013,1987,High,Tier 3,Supermarket Type1,994.7052
5,FDP36,10.395,Regular,0.000000,Baking Goods,51.4008,OUT018,2009,Medium,Tier 3,Supermarket Type2,556.6088
6,FDO10,13.650,Regular,0.012741,Snack Foods,57.6588,OUT013,1987,High,Tier 3,Supermarket Type1,343.5528
7,FDP10,NaN,Low Fat,0.127470,Snack Foods,107.7622,OUT027,1985,Medium,Tier 3,Supermarket Type3,4022.7636
8,FDH17,16.200,Regular,0.016687,Frozen Foods,96.9726,OUT045,2002,NaN,Tier 2,Supermarket Type1,1076.5986
9,FDU28,19.200,Regular,0.094450,Frozen Foods,187.8214,OUT017,2007,NaN,Tier 2,Supermarket Type1,4710.5350
10,FDY07,11.800,Low Fat,0.000000,Fruits and Vegetables,45.5402,OUT049,1999,Medium,Tier 1,Supermarket Type1,1516.0266
11,FDA03,18.500,Regular,0.045464,Dairy,144.1102,OUT046,1997,Small,Tier 1,Supermarket Type1,2187.1530
12,FDX32,15.100,Regular,0.100014,Fruits and Vegetables,145.4786,OUT049,1999,Medium,Tier 1,Supermarket Type1,1589.2646
13,FDS46,17.600,Regular,0.047257,Snack Foods,119.6782,OUT046,1997,Small,Tier 1,Supermarket Type1,2145.2076
14,FDF32,16.350,Low Fat,0.068024,Fruits and Vegetables,196.4426,OUT013,1987,High,Tier 3,Supermarket Type1,1977.4260

In [3]:
A.shape

(8523, 12)

In [4]:
A.columns

Index(['Item_Identifier', 'Item_Weight', 'Item_Fat_Content', 'Item_Visibility',
       'Item_Type', 'Item_MRP', 'Outlet_Identifier',
       'Outlet_Establishment_Year', 'Outlet_Size', 'Outlet_Location_Type',
       'Outlet_Type', 'Item_Outlet_Sales'],
      dtype='object')

# Feature selection

In [5]:
Y = A[["Item_Outlet_Sales"]]
A = A.drop(columns=["Item_Identifier","Outlet_Identifier"],axis=1)

# Missing data treatment and Cat, Con seperation

In [6]:
from PM6 import seperate,ANOVA,replacer
replacer(A)
q = list(A.columns)
q.remove("Item_Outlet_Sales")

con,cat =seperate(A)

In [7]:
cat

['Item_Fat_Content',
 'Item_Type',
 'Outlet_Size',
 'Outlet_Location_Type',
 'Outlet_Type']

In [8]:
con

['Item_Weight',
 'Item_Visibility',
 'Item_MRP',
 'Outlet_Establishment_Year',
 'Item_Outlet_Sales']

In [9]:
imp_cat = []
q=list(cat)
for i in q :    
        print("--------------------")
        print("Item_Outlet_Sales vs",i)
        w = ANOVA(A,i,"Item_Outlet_Sales")
        print(w)
        if(w < 0.05):
            imp_cat.append(i)

--------------------
Item_Outlet_Sales vs Item_Fat_Content
0.1412
--------------------
Item_Outlet_Sales vs Item_Type
0.0004
--------------------
Item_Outlet_Sales vs Outlet_Size
0.0
--------------------
Item_Outlet_Sales vs Outlet_Location_Type
0.0
--------------------
Item_Outlet_Sales vs Outlet_Type
0.0

In [10]:
imp_con = []
Q = A[con].corr()["Item_Outlet_Sales"].sort_values()
imp_con = list(Q[(Q < 1)&(Q > 0.3)].index)
print(Q)

Item_Visibility             -0.128625
Outlet_Establishment_Year   -0.049135
Item_Weight                  0.011550
Item_MRP                     0.567574
Item_Outlet_Sales            1.000000
Name: Item_Outlet_Sales, dtype: float64

In [11]:
imp_cat

['Item_Type', 'Outlet_Size', 'Outlet_Location_Type', 'Outlet_Type']

In [12]:
imp_con

['Item_MRP']

In [13]:
A = A[imp_cat].join(A[imp_con])

In [14]:
A.head()

,Item_Type,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_MRP
0,Dairy,Medium,Tier 1,Supermarket Type1,249.8092
1,Soft Drinks,Medium,Tier 3,Supermarket Type2,48.2692
2,Meat,Medium,Tier 1,Supermarket Type1,141.6180
3,Fruits and Vegetables,Medium,Tier 3,Grocery Store,182.0950
4,Household,High,Tier 3,Supermarket Type1,53.8614

In [15]:
A.shape

(8523, 5)

In [16]:
from PM6 import preprocessing
X =preprocessing(A)
X.head()

,Item_MRP,Item_Type_Baking Goods,Item_Type_Breads,Item_Type_Breakfast,Item_Type_Canned,Item_Type_Dairy,Item_Type_Frozen Foods,Item_Type_Fruits and Vegetables,Item_Type_Hard Drinks,Item_Type_Health and Hygiene,...,Outlet_Size_High,Outlet_Size_Medium,Outlet_Size_Small,Outlet_Location_Type_Tier 1,Outlet_Location_Type_Tier 2,Outlet_Location_Type_Tier 3,Outlet_Type_Grocery Store,Outlet_Type_Supermarket Type1,Outlet_Type_Supermarket Type2,Outlet_Type_Supermarket Type3
0,1.747454,0,0,0,0,1,0,0,0,0,...,0,1,0,1,0,0,0,1,0,0
1,-1.489023,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,1,0,0,1,0
2,0.010040,0,0,0,0,0,0,0,0,0,...,0,1,0,1,0,0,0,1,0,0
3,0.660050,0,0,0,0,0,0,1,0,0,...,0,1,0,0,0,1,1,0,0,0
4,-1.399220,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,1,0,1,0,0

In [17]:
X

,Item_MRP,Item_Type_Baking Goods,Item_Type_Breads,Item_Type_Breakfast,Item_Type_Canned,Item_Type_Dairy,Item_Type_Frozen Foods,Item_Type_Fruits and Vegetables,Item_Type_Hard Drinks,Item_Type_Health and Hygiene,...,Outlet_Size_High,Outlet_Size_Medium,Outlet_Size_Small,Outlet_Location_Type_Tier 1,Outlet_Location_Type_Tier 2,Outlet_Location_Type_Tier 3,Outlet_Type_Grocery Store,Outlet_Type_Supermarket Type1,Outlet_Type_Supermarket Type2,Outlet_Type_Supermarket Type3
0,1.747454,0,0,0,0,1,0,0,0,0,...,0,1,0,1,0,0,0,1,0,0
1,-1.489023,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,1,0,0,1,0
2,0.010040,0,0,0,0,0,0,0,0,0,...,0,1,0,1,0,0,0,1,0,0
3,0.660050,0,0,0,0,0,0,1,0,0,...,0,1,0,0,0,1,1,0,0,0
4,-1.399220,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,1,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8518,1.180783,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,1,0,1,0,0
8519,-0.527301,1,0,0,0,0,0,0,0,0,...,0,1,0,0,1,0,0,1,0,0
8520,-0.897208,0,0,0,0,0,0,0,0,1,...,0,0,1,0,1,0,0,1,0,0
8521,-0.607977,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,1,0,0,1,0
8522,-1.052261,0,0,0,0,0,0,0,0,0,...,0,0,1,1,0,0,0,1,0,0

In [18]:
X.skew().sort_values

<bound method Series.sort_values of Item_MRP                            0.127202
Item_Type_Baking Goods              3.199792
Item_Type_Breads                    5.567533
Item_Type_Breakfast                 8.632562
Item_Type_Canned                    3.196644
Item_Type_Dairy                     3.096356
Item_Type_Frozen Foods              2.659119
Item_Type_Fruits and Vegetables     2.021988
Item_Type_Hard Drinks               6.071724
Item_Type_Health and Hygiene        3.668801
Item_Type_Household                 2.547106
Item_Type_Meat                      4.136741
Item_Type_Others                    6.889767
Item_Type_Seafood                  11.411629
Item_Type_Snack Foods               2.065882
Item_Type_Soft Drinks               4.026612
Item_Type_Starchy Foods             7.390855
Outlet_Size_High                    2.503964
Outlet_Size_Medium                 -0.453138
Outlet_Size_Small                   0.979119
Outlet_Location_Type_Tier 1         0.979119
Outlet_Location_Type_Tier 2         0.738834
Outlet_Location_Type_Tier 3         0.437995
Outlet_Type_Grocery Store           2.239897
Outlet_Type_Supermarket Type1      -0.649203
Outlet_Type_Supermarket Type2       2.511707
Outlet_Type_Supermarket Type3       2.498184
dtype: float64>

In [19]:
S = X.skew()
skew = list(S[S>2].index)
skew

['Item_Type_Baking Goods',
 'Item_Type_Breads',
 'Item_Type_Breakfast',
 'Item_Type_Canned',
 'Item_Type_Dairy',
 'Item_Type_Frozen Foods',
 'Item_Type_Fruits and Vegetables',
 'Item_Type_Hard Drinks',
 'Item_Type_Health and Hygiene',
 'Item_Type_Household',
 'Item_Type_Meat',
 'Item_Type_Others',
 'Item_Type_Seafood',
 'Item_Type_Snack Foods',
 'Item_Type_Soft Drinks',
 'Item_Type_Starchy Foods',
 'Outlet_Size_High',
 'Outlet_Type_Grocery Store',
 'Outlet_Type_Supermarket Type2',
 'Outlet_Type_Supermarket Type3']

In [20]:
import numpy as np
from numpy import log
for j in skew:
    W = []
    for i in X[j]:
        if(i != 0):
            W.append(np.log(i))
        else:
            W.append(i)
    X[j] = W

In [21]:
X.skew()

Item_MRP                           0.127202
Item_Type_Baking Goods             0.000000
Item_Type_Breads                   0.000000
Item_Type_Breakfast                0.000000
Item_Type_Canned                   0.000000
Item_Type_Dairy                    0.000000
Item_Type_Frozen Foods             0.000000
Item_Type_Fruits and Vegetables    0.000000
Item_Type_Hard Drinks              0.000000
Item_Type_Health and Hygiene       0.000000
Item_Type_Household                0.000000
Item_Type_Meat                     0.000000
Item_Type_Others                   0.000000
Item_Type_Seafood                  0.000000
Item_Type_Snack Foods              0.000000
Item_Type_Soft Drinks              0.000000
Item_Type_Starchy Foods            0.000000
Outlet_Size_High                   0.000000
Outlet_Size_Medium                -0.453138
Outlet_Size_Small                  0.979119
Outlet_Location_Type_Tier 1        0.979119
Outlet_Location_Type_Tier 2        0.738834
Outlet_Location_Type_Tier 3        0.437995
Outlet_Type_Grocery Store          0.000000
Outlet_Type_Supermarket Type1     -0.649203
Outlet_Type_Supermarket Type2      0.000000
Outlet_Type_Supermarket Type3      0.000000
dtype: float64

In [22]:
X.shape

(8523, 27)

In [23]:
X.columns

Index(['Item_MRP', 'Item_Type_Baking Goods', 'Item_Type_Breads',
       'Item_Type_Breakfast', 'Item_Type_Canned', 'Item_Type_Dairy',
       'Item_Type_Frozen Foods', 'Item_Type_Fruits and Vegetables',
       'Item_Type_Hard Drinks', 'Item_Type_Health and Hygiene',
       'Item_Type_Household', 'Item_Type_Meat', 'Item_Type_Others',
       'Item_Type_Seafood', 'Item_Type_Snack Foods', 'Item_Type_Soft Drinks',
       'Item_Type_Starchy Foods', 'Outlet_Size_High', 'Outlet_Size_Medium',
       'Outlet_Size_Small', 'Outlet_Location_Type_Tier 1',
       'Outlet_Location_Type_Tier 2', 'Outlet_Location_Type_Tier 3',
       'Outlet_Type_Grocery Store', 'Outlet_Type_Supermarket Type1',
       'Outlet_Type_Supermarket Type2', 'Outlet_Type_Supermarket Type3'],
      dtype='object')

In [24]:
Q =['Item_MRP', 'Item_Type_Baking Goods', 'Item_Type_Breads',
        'Item_Type_Breakfast', 'Item_Type_Canned', 'Item_Type_Dairy',
        'Item_Type_Frozen Foods', 'Item_Type_Fruits and Vegetables',
        'Item_Type_Hard Drinks', 'Item_Type_Health and Hygiene',
        'Item_Type_Household', 'Item_Type_Meat', 'Item_Type_Others',
        'Item_Type_Seafood', 'Item_Type_Snack Foods', 'Item_Type_Soft Drinks',
        'Item_Type_Starchy Foods', 'Outlet_Size_High', 'Outlet_Size_Medium',
        'Outlet_Size_Small', 'Outlet_Location_Type_Tier 1',
        'Outlet_Location_Type_Tier 2', 'Outlet_Location_Type_Tier 3',
        'Outlet_Type_Grocery Store', 'Outlet_Type_Supermarket Type1',
        'Outlet_Type_Supermarket Type2', 'Outlet_Type_Supermarket Type3']

In [25]:
Q[0:2]

['Item_MRP', 'Item_Type_Baking Goods']

In [26]:
for i in Q:
    j = Q[0:Q.index(i)+1]
    Xnew = X[j]
    print("Selected columns:",Xnew.columns)
    from sklearn.model_selection import train_test_split
    xtrain,xtest,ytrain,ytest = train_test_split(Xnew,Y,test_size=0.2,random_state=21)
    from sklearn.linear_model import LinearRegression
    lm=LinearRegression()
    model = lm.fit(xtrain,ytrain)
    pred = model.predict(xtest)
    from sklearn.metrics import mean_squared_error
    
    mse1 = round(mean_squared_error(ytest,pred),4)
    print("\n Mean squared error is:",mse1)

Selected columns: Index(['Item_MRP'], dtype='object')

 Mean squared error is: 1955149.4651
Selected columns: Index(['Item_MRP', 'Item_Type_Baking Goods'], dtype='object')

 Mean squared error is: 1955149.4651
Selected columns: Index(['Item_MRP', 'Item_Type_Baking Goods', 'Item_Type_Breads'], dtype='object')

 Mean squared error is: 1955149.4651
Selected columns: Index(['Item_MRP', 'Item_Type_Baking Goods', 'Item_Type_Breads',
       'Item_Type_Breakfast'],
      dtype='object')

 Mean squared error is: 1955149.4651
Selected columns: Index(['Item_MRP', 'Item_Type_Baking Goods', 'Item_Type_Breads',
       'Item_Type_Breakfast', 'Item_Type_Canned'],
      dtype='object')

 Mean squared error is: 1955149.4651
Selected columns: Index(['Item_MRP', 'Item_Type_Baking Goods', 'Item_Type_Breads',
       'Item_Type_Breakfast', 'Item_Type_Canned', 'Item_Type_Dairy'],
      dtype='object')

 Mean squared error is: 1955149.4651
Selected columns: Index(['Item_MRP', 'Item_Type_Baking Goods', 'Item_Type_Breads',
       'Item_Type_Breakfast', 'Item_Type_Canned', 'Item_Type_Dairy',
       'Item_Type_Frozen Foods'],
      dtype='object')

 Mean squared error is: 1955149.4651
Selected columns: Index(['Item_MRP', 'Item_Type_Baking Goods', 'Item_Type_Breads',
       'Item_Type_Breakfast', 'Item_Type_Canned', 'Item_Type_Dairy',
       'Item_Type_Frozen Foods', 'Item_Type_Fruits and Vegetables'],
      dtype='object')

 Mean squared error is: 1955149.4651
Selected columns: Index(['Item_MRP', 'Item_Type_Baking Goods', 'Item_Type_Breads',
       'Item_Type_Breakfast', 'Item_Type_Canned', 'Item_Type_Dairy',
       'Item_Type_Frozen Foods', 'Item_Type_Fruits and Vegetables',
       'Item_Type_Hard Drinks'],
      dtype='object')

 Mean squared error is: 1955149.4651
Selected columns: Index(['Item_MRP', 'Item_Type_Baking Goods', 'Item_Type_Breads',
       'Item_Type_Breakfast', 'Item_Type_Canned', 'Item_Type_Dairy',
       'Item_Type_Frozen Foods', 'Item_Type_Fruits and Vegetables',
       'Item_Type_Hard Drinks', 'Item_Type_Health and Hygiene'],
      dtype='object')

 Mean squared error is: 1955149.4651
Selected columns: Index(['Item_MRP', 'Item_Type_Baking Goods', 'Item_Type_Breads',
       'Item_Type_Breakfast', 'Item_Type_Canned', 'Item_Type_Dairy',
       'Item_Type_Frozen Foods', 'Item_Type_Fruits and Vegetables',
       'Item_Type_Hard Drinks', 'Item_Type_Health and Hygiene',
       'Item_Type_Household'],
      dtype='object')

 Mean squared error is: 1955149.4651
Selected columns: Index(['Item_MRP', 'Item_Type_Baking Goods', 'Item_Type_Breads',
       'Item_Type_Breakfast', 'Item_Type_Canned', 'Item_Type_Dairy',
       'Item_Type_Frozen Foods', 'Item_Type_Fruits and Vegetables',
       'Item_Type_Hard Drinks', 'Item_Type_Health and Hygiene',
       'Item_Type_Household', 'Item_Type_Meat'],
      dtype='object')

 Mean squared error is: 1955149.4651
Selected columns: Index(['Item_MRP', 'Item_Type_Baking Goods', 'Item_Type_Breads',
       'Item_Type_Breakfast', 'Item_Type_Canned', 'Item_Type_Dairy',
       'Item_Type_Frozen Foods', 'Item_Type_Fruits and Vegetables',
       'Item_Type_Hard Drinks', 'Item_Type_Health and Hygiene',
       'Item_Type_Household', 'Item_Type_Meat', 'Item_Type_Others'],
      dtype='object')

 Mean squared error is: 1955149.4651
Selected columns: Index(['Item_MRP', 'Item_Type_Baking Goods', 'Item_Type_Breads',
       'Item_Type_Breakfast', 'Item_Type_Canned', 'Item_Type_Dairy',
       'Item_Type_Frozen Foods', 'Item_Type_Fruits and Vegetables',
       'Item_Type_Hard Drinks', 'Item_Type_Health and Hygiene',
       'Item_Type_Household', 'Item_Type_Meat', 'Item_Type_Others',
       'Item_Type_Seafood'],
      dtype='object')

 Mean squared error is: 1955149.4651
Selected columns: Index(['Item_MRP', 'Item_Type_Baking Goods', 'Item_Type_Breads',
       'Item_Type_Breakfast', 'Item_Type_Canned', 'Item_Type_Dairy',
       'Item_Type_Frozen Foods', 'Item_Type_Fruits and Vegetables',
       'Item_Type_Hard Drinks', 'Item_Type_Health and Hygiene',
       'Item_Type_Household', 'Item_Type_Meat', 'Item_Type_Others',
       'Item_Type_Seafood', 'Item_Type_Snack Foods'],
      dtype='object')

 Mean squared error is: 1955149.4651
Selected columns: Index(['Item_MRP', 'Item_Type_Baking Goods', 'Item_Type_Breads',
       'Item_Type_Breakfast', 'Item_Type_Canned', 'Item_Type_Dairy',
       'Item_Type_Frozen Foods', 'Item_Type_Fruits and Vegetables',
       'Item_Type_Hard Drinks', 'Item_Type_Health and Hygiene',
       'Item_Type_Household', 'Item_Type_Meat', 'Item_Type_Others',
       'Item_Type_Seafood', 'Item_Type_Snack Foods', 'Item_Type_Soft Drinks'],
      dtype='object')

 Mean squared error is: 1955149.4651
Selected columns: Index(['Item_MRP', 'Item_Type_Baking Goods', 'Item_Type_Breads',
       'Item_Type_Breakfast', 'Item_Type_Canned', 'Item_Type_Dairy',
       'Item_Type_Frozen Foods', 'Item_Type_Fruits and Vegetables',
       'Item_Type_Hard Drinks', 'Item_Type_Health and Hygiene',
       'Item_Type_Household', 'Item_Type_Meat', 'Item_Type_Others',
       'Item_Type_Seafood', 'Item_Type_Snack Foods', 'Item_Type_Soft Drinks',
       'Item_Type_Starchy Foods'],
      dtype='object')

 Mean squared error is: 1955149.4651
Selected columns: Index(['Item_MRP', 'Item_Type_Baking Goods', 'Item_Type_Breads',
       'Item_Type_Breakfast', 'Item_Type_Canned', 'Item_Type_Dairy',
       'Item_Type_Frozen Foods', 'Item_Type_Fruits and Vegetables',
       'Item_Type_Hard Drinks', 'Item_Type_Health and Hygiene',
       'Item_Type_Household', 'Item_Type_Meat', 'Item_Type_Others',
       'Item_Type_Seafood', 'Item_Type_Snack Foods', 'Item_Type_Soft Drinks',
       'Item_Type_Starchy Foods', 'Outlet_Size_High'],
      dtype='object')

 Mean squared error is: 1955149.4651
Selected columns: Index(['Item_MRP', 'Item_Type_Baking Goods', 'Item_Type_Breads',
       'Item_Type_Breakfast', 'Item_Type_Canned', 'Item_Type_Dairy',
       'Item_Type_Frozen Foods', 'Item_Type_Fruits and Vegetables',
       'Item_Type_Hard Drinks', 'Item_Type_Health and Hygiene',
       'Item_Type_Household', 'Item_Type_Meat', 'Item_Type_Others',
       'Item_Type_Seafood', 'Item_Type_Snack Foods', 'Item_Type_Soft Drinks',
       'Item_Type_Starchy Foods', 'Outlet_Size_High', 'Outlet_Size_Medium'],
      dtype='object')

 Mean squared error is: 1924558.1083
Selected columns: Index(['Item_MRP', 'Item_Type_Baking Goods', 'Item_Type_Breads',
       'Item_Type_Breakfast', 'Item_Type_Canned', 'Item_Type_Dairy',
       'Item_Type_Frozen Foods', 'Item_Type_Fruits and Vegetables',
       'Item_Type_Hard Drinks', 'Item_Type_Health and Hygiene',
       'Item_Type_Household', 'Item_Type_Meat', 'Item_Type_Others',
       'Item_Type_Seafood', 'Item_Type_Snack Foods', 'Item_Type_Soft Drinks',
       'Item_Type_Starchy Foods', 'Outlet_Size_High', 'Outlet_Size_Medium',
       'Outlet_Size_Small'],
      dtype='object')

 Mean squared error is: 1913772.3818
Selected columns: Index(['Item_MRP', 'Item_Type_Baking Goods', 'Item_Type_Breads',
       'Item_Type_Breakfast', 'Item_Type_Canned', 'Item_Type_Dairy',
       'Item_Type_Frozen Foods', 'Item_Type_Fruits and Vegetables',
       'Item_Type_Hard Drinks', 'Item_Type_Health and Hygiene',
       'Item_Type_Household', 'Item_Type_Meat', 'Item_Type_Others',
       'Item_Type_Seafood', 'Item_Type_Snack Foods', 'Item_Type_Soft Drinks',
       'Item_Type_Starchy Foods', 'Outlet_Size_High', 'Outlet_Size_Medium',
       'Outlet_Size_Small', 'Outlet_Location_Type_Tier 1'],
      dtype='object')

 Mean squared error is: 1901874.2453
Selected columns: Index(['Item_MRP', 'Item_Type_Baking Goods', 'Item_Type_Breads',
       'Item_Type_Breakfast', 'Item_Type_Canned', 'Item_Type_Dairy',
       'Item_Type_Frozen Foods', 'Item_Type_Fruits and Vegetables',
       'Item_Type_Hard Drinks', 'Item_Type_Health and Hygiene',
       'Item_Type_Household', 'Item_Type_Meat', 'Item_Type_Others',
       'Item_Type_Seafood', 'Item_Type_Snack Foods', 'Item_Type_Soft Drinks',
       'Item_Type_Starchy Foods', 'Outlet_Size_High', 'Outlet_Size_Medium',
       'Outlet_Size_Small', 'Outlet_Location_Type_Tier 1',
       'Outlet_Location_Type_Tier 2'],
      dtype='object')

 Mean squared error is: 1909000.134
Selected columns: Index(['Item_MRP', 'Item_Type_Baking Goods', 'Item_Type_Breads',
       'Item_Type_Breakfast', 'Item_Type_Canned', 'Item_Type_Dairy',
       'Item_Type_Frozen Foods', 'Item_Type_Fruits and Vegetables',
       'Item_Type_Hard Drinks', 'Item_Type_Health and Hygiene',
       'Item_Type_Household', 'Item_Type_Meat', 'Item_Type_Others',
       'Item_Type_Seafood', 'Item_Type_Snack Foods', 'Item_Type_Soft Drinks',
       'Item_Type_Starchy Foods', 'Outlet_Size_High', 'Outlet_Size_Medium',
       'Outlet_Size_Small', 'Outlet_Location_Type_Tier 1',
       'Outlet_Location_Type_Tier 2', 'Outlet_Location_Type_Tier 3'],
      dtype='object')

 Mean squared error is: 1909000.134
Selected columns: Index(['Item_MRP', 'Item_Type_Baking Goods', 'Item_Type_Breads',
       'Item_Type_Breakfast', 'Item_Type_Canned', 'Item_Type_Dairy',
       'Item_Type_Frozen Foods', 'Item_Type_Fruits and Vegetables',
       'Item_Type_Hard Drinks', 'Item_Type_Health and Hygiene',
       'Item_Type_Household', 'Item_Type_Meat', 'Item_Type_Others',
       'Item_Type_Seafood', 'Item_Type_Snack Foods', 'Item_Type_Soft Drinks',
       'Item_Type_Starchy Foods', 'Outlet_Size_High', 'Outlet_Size_Medium',
       'Outlet_Size_Small', 'Outlet_Location_Type_Tier 1',
       'Outlet_Location_Type_Tier 2', 'Outlet_Location_Type_Tier 3',
       'Outlet_Type_Grocery Store'],
      dtype='object')

 Mean squared error is: 1909000.134
Selected columns: Index(['Item_MRP', 'Item_Type_Baking Goods', 'Item_Type_Breads',
       'Item_Type_Breakfast', 'Item_Type_Canned', 'Item_Type_Dairy',
       'Item_Type_Frozen Foods', 'Item_Type_Fruits and Vegetables',
       'Item_Type_Hard Drinks', 'Item_Type_Health and Hygiene',
       'Item_Type_Household', 'Item_Type_Meat', 'Item_Type_Others',
       'Item_Type_Seafood', 'Item_Type_Snack Foods', 'Item_Type_Soft Drinks',
       'Item_Type_Starchy Foods', 'Outlet_Size_High', 'Outlet_Size_Medium',
       'Outlet_Size_Small', 'Outlet_Location_Type_Tier 1',
       'Outlet_Location_Type_Tier 2', 'Outlet_Location_Type_Tier 3',
       'Outlet_Type_Grocery Store', 'Outlet_Type_Supermarket Type1'],
      dtype='object')

 Mean squared error is: 1722331.502
Selected columns: Index(['Item_MRP', 'Item_Type_Baking Goods', 'Item_Type_Breads',
       'Item_Type_Breakfast', 'Item_Type_Canned', 'Item_Type_Dairy',
       'Item_Type_Frozen Foods', 'Item_Type_Fruits and Vegetables',
       'Item_Type_Hard Drinks', 'Item_Type_Health and Hygiene',
       'Item_Type_Household', 'Item_Type_Meat', 'Item_Type_Others',
       'Item_Type_Seafood', 'Item_Type_Snack Foods', 'Item_Type_Soft Drinks',
       'Item_Type_Starchy Foods', 'Outlet_Size_High', 'Outlet_Size_Medium',
       'Outlet_Size_Small', 'Outlet_Location_Type_Tier 1',
       'Outlet_Location_Type_Tier 2', 'Outlet_Location_Type_Tier 3',
       'Outlet_Type_Grocery Store', 'Outlet_Type_Supermarket Type1',
       'Outlet_Type_Supermarket Type2'],
      dtype='object')

 Mean squared error is: 1722331.502
Selected columns: Index(['Item_MRP', 'Item_Type_Baking Goods', 'Item_Type_Breads',
       'Item_Type_Breakfast', 'Item_Type_Canned', 'Item_Type_Dairy',
       'Item_Type_Frozen Foods', 'Item_Type_Fruits and Vegetables',
       'Item_Type_Hard Drinks', 'Item_Type_Health and Hygiene',
       'Item_Type_Household', 'Item_Type_Meat', 'Item_Type_Others',
       'Item_Type_Seafood', 'Item_Type_Snack Foods', 'Item_Type_Soft Drinks',
       'Item_Type_Starchy Foods', 'Outlet_Size_High', 'Outlet_Size_Medium',
       'Outlet_Size_Small', 'Outlet_Location_Type_Tier 1',
       'Outlet_Location_Type_Tier 2', 'Outlet_Location_Type_Tier 3',
       'Outlet_Type_Grocery Store', 'Outlet_Type_Supermarket Type1',
       'Outlet_Type_Supermarket Type2', 'Outlet_Type_Supermarket Type3'],
      dtype='object')

 Mean squared error is: 1722331.502

# As last value of mean squared error is minumum out of all, Model with all coulmns is  the best model

In [27]:
Xnew = X
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest = train_test_split(Xnew,Y,test_size=0.2,random_state=21)
from sklearn.linear_model import LinearRegression
lm=LinearRegression()
model = lm.fit(xtrain,ytrain)
pred = model.predict(xtest)
from sklearn.metrics import mean_squared_error
    
mse1 = round(mean_squared_error(ytest,pred),4)
print("\n Mean squared error is:",mse1)

 Mean squared error is: 1722331.502

# Predicting sale of each product at perticular store

In [28]:
Xt=pd.read_csv("D:/My work/Data science course/Datasets/Test.csv")

In [29]:
Xt.head()

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type
0,FDW58,20.750,Low Fat,0.007565,Snack Foods,107.8622,OUT049,1999,Medium,Tier 1,Supermarket Type1
1,FDW14,8.300,reg,0.038428,Dairy,87.3198,OUT017,2007,NaN,Tier 2,Supermarket Type1
2,NCN55,14.600,Low Fat,0.099575,Others,241.7538,OUT010,1998,NaN,Tier 3,Grocery Store
3,FDQ58,7.315,Low Fat,0.015388,Snack Foods,155.0340,OUT017,2007,NaN,Tier 2,Supermarket Type1
4,FDY38,NaN,Regular,0.118599,Dairy,234.2300,OUT027,1985,Medium,Tier 3,Supermarket Type3

In [30]:
Xt = Xt.drop(columns=["Item_Identifier","Outlet_Identifier"],axis=1)

In [31]:
Xt1 = replacer(Xt)
Xt1 = preprocessing(Xt)

In [32]:
Xt1.columns

Index(['Item_Weight', 'Item_Visibility', 'Item_MRP',
       'Outlet_Establishment_Year', 'Item_Fat_Content_LF',
       'Item_Fat_Content_Low Fat', 'Item_Fat_Content_Regular',
       'Item_Fat_Content_low fat', 'Item_Fat_Content_reg',
       'Item_Type_Baking Goods', 'Item_Type_Breads', 'Item_Type_Breakfast',
       'Item_Type_Canned', 'Item_Type_Dairy', 'Item_Type_Frozen Foods',
       'Item_Type_Fruits and Vegetables', 'Item_Type_Hard Drinks',
       'Item_Type_Health and Hygiene', 'Item_Type_Household', 'Item_Type_Meat',
       'Item_Type_Others', 'Item_Type_Seafood', 'Item_Type_Snack Foods',
       'Item_Type_Soft Drinks', 'Item_Type_Starchy Foods', 'Outlet_Size_High',
       'Outlet_Size_Medium', 'Outlet_Size_Small',
       'Outlet_Location_Type_Tier 1', 'Outlet_Location_Type_Tier 2',
       'Outlet_Location_Type_Tier 3', 'Outlet_Type_Grocery Store',
       'Outlet_Type_Supermarket Type1', 'Outlet_Type_Supermarket Type2',
       'Outlet_Type_Supermarket Type3'],
      dtype='object')

In [33]:
Xtnew=Xt1[Q]

In [34]:
Xtnew.head(2)

,Item_MRP,Item_Type_Baking Goods,Item_Type_Breads,Item_Type_Breakfast,Item_Type_Canned,Item_Type_Dairy,Item_Type_Frozen Foods,Item_Type_Fruits and Vegetables,Item_Type_Hard Drinks,Item_Type_Health and Hygiene,...,Outlet_Size_High,Outlet_Size_Medium,Outlet_Size_Small,Outlet_Location_Type_Tier 1,Outlet_Location_Type_Tier 2,Outlet_Location_Type_Tier 3,Outlet_Type_Grocery Store,Outlet_Type_Supermarket Type1,Outlet_Type_Supermarket Type2,Outlet_Type_Supermarket Type3
0,-0.536555,0,0,0,0,0,0,0,0,0,...,0,1,0,1,0,0,0,1,0,0
1,-0.868937,0,0,0,0,1,0,0,0,0,...,0,1,0,0,1,0,0,1,0,0

In [35]:
Xtnew.skew()

Item_MRP                            0.136182
Item_Type_Baking Goods              3.171620
Item_Type_Breads                    5.610422
Item_Type_Breakfast                 8.473575
Item_Type_Canned                    3.185600
Item_Type_Dairy                     3.099217
Item_Type_Frozen Foods              2.661190
Item_Type_Fruits and Vegetables     2.106119
Item_Type_Hard Drinks               5.952360
Item_Type_Health and Hygiene        3.725356
Item_Type_Household                 2.456438
Item_Type_Meat                      3.915724
Item_Type_Others                    6.944464
Item_Type_Seafood                  14.978748
Item_Type_Snack Foods               2.088981
Item_Type_Soft Drinks               4.156711
Item_Type_Starchy Foods             6.632903
Outlet_Size_High                    2.504833
Outlet_Size_Medium                 -0.453136
Outlet_Size_Small                   0.978933
Outlet_Location_Type_Tier 1         0.978933
Outlet_Location_Type_Tier 2         0.739189
Outlet_Location_Type_Tier 3         0.437989
Outlet_Type_Grocery Store           2.239791
Outlet_Type_Supermarket Type1      -0.648977
Outlet_Type_Supermarket Type2       2.513554
Outlet_Type_Supermarket Type3       2.496167
dtype: float64

In [36]:
St = Xtnew.skew()
skewt = list(S[S>2].index)
skewt

['Item_Type_Baking Goods',
 'Item_Type_Breads',
 'Item_Type_Breakfast',
 'Item_Type_Canned',
 'Item_Type_Dairy',
 'Item_Type_Frozen Foods',
 'Item_Type_Fruits and Vegetables',
 'Item_Type_Hard Drinks',
 'Item_Type_Health and Hygiene',
 'Item_Type_Household',
 'Item_Type_Meat',
 'Item_Type_Others',
 'Item_Type_Seafood',
 'Item_Type_Snack Foods',
 'Item_Type_Soft Drinks',
 'Item_Type_Starchy Foods',
 'Outlet_Size_High',
 'Outlet_Type_Grocery Store',
 'Outlet_Type_Supermarket Type2',
 'Outlet_Type_Supermarket Type3']

In [37]:
for j in skewt:
    W = []
    for i in Xtnew[j]:
        if(i != 0):
            W.append(np.log(i))
        else:
            W.append(i)
    Xtnew[j] = W

In [38]:
Xtnew.skew()

Item_MRP                           0.136182
Item_Type_Baking Goods             0.000000
Item_Type_Breads                   0.000000
Item_Type_Breakfast                0.000000
Item_Type_Canned                   0.000000
Item_Type_Dairy                    0.000000
Item_Type_Frozen Foods             0.000000
Item_Type_Fruits and Vegetables    0.000000
Item_Type_Hard Drinks              0.000000
Item_Type_Health and Hygiene       0.000000
Item_Type_Household                0.000000
Item_Type_Meat                     0.000000
Item_Type_Others                   0.000000
Item_Type_Seafood                  0.000000
Item_Type_Snack Foods              0.000000
Item_Type_Soft Drinks              0.000000
Item_Type_Starchy Foods            0.000000
Outlet_Size_High                   0.000000
Outlet_Size_Medium                -0.453136
Outlet_Size_Small                  0.978933
Outlet_Location_Type_Tier 1        0.978933
Outlet_Location_Type_Tier 2        0.739189
Outlet_Location_Type_Tier 3        0.437989
Outlet_Type_Grocery Store          0.000000
Outlet_Type_Supermarket Type1     -0.648977
Outlet_Type_Supermarket Type2      0.000000
Outlet_Type_Supermarket Type3      0.000000
dtype: float64

In [39]:
predicted = model.predict(Xtnew)

In [40]:
D =pd.read_csv("D:/My work/Data science course/Datasets/Test.csv")
T = D[["Outlet_Identifier"]]
T["Item_Outlet_Sales"] = predicted

In [41]:
T.head(10)

  Outlet_Identifier  Item_Outlet_Sales
0            OUT049        1765.956357
1            OUT017        1493.037661
2            OUT010        3820.678240
3            OUT017        2550.451086
4            OUT027        3703.187860
5            OUT046        1945.735650
6            OUT018         827.898207
7            OUT027        1311.298712
8            OUT045        1624.582289
9            OUT017        3047.946439

In [42]:
T.to_csv("Desktop/predicted_sales_pro2.csv",index=None)

# Thus sales of each product at a particular store is predicted

# Properties of products and stores which play a key role in increasing sales are listed below.

In [43]:
properties = Xtnew.columns

In [44]:
properties

Index(['Item_MRP', 'Item_Type_Baking Goods', 'Item_Type_Breads',
       'Item_Type_Breakfast', 'Item_Type_Canned', 'Item_Type_Dairy',
       'Item_Type_Frozen Foods', 'Item_Type_Fruits and Vegetables',
       'Item_Type_Hard Drinks', 'Item_Type_Health and Hygiene',
       'Item_Type_Household', 'Item_Type_Meat', 'Item_Type_Others',
       'Item_Type_Seafood', 'Item_Type_Snack Foods', 'Item_Type_Soft Drinks',
       'Item_Type_Starchy Foods', 'Outlet_Size_High', 'Outlet_Size_Medium',
       'Outlet_Size_Small', 'Outlet_Location_Type_Tier 1',
       'Outlet_Location_Type_Tier 2', 'Outlet_Location_Type_Tier 3',
       'Outlet_Type_Grocery Store', 'Outlet_Type_Supermarket Type1',
       'Outlet_Type_Supermarket Type2', 'Outlet_Type_Supermarket Type3'],
      dtype='object')

# Following properties of products and stores play a key role in increasing   sales   

        Item_MRP
        Item_Type
        Outlet_Size
        Outlet_Location_Type
        Outlet_Type